import { StyleSheet } from 'react-native';

export const DoctorReviewScreenStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#ADD8E6',
    paddingTop: 40,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 15,
    marginBottom: 20,
  },
  backButton: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  backButtonText: {
    marginLeft: 5,
    fontSize: 16,
  },
  headerMenuButton: {},
  headerTitle: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  headerSettingsButton: {},
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 25,
    marginHorizontal: 15,
    paddingHorizontal: 15,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  searchInput: {
    flex: 1,
    height: 40,
    color: '#000',
  },
  searchIcon: {
    marginLeft: 10,
  },
  scrollView: {
    flex: 1,
  },
  doctorInfoContainer: {
    backgroundColor: '#fff',
    marginHorizontal: 15,
    borderRadius: 10,
    padding: 20,
    alignItems: 'center',
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  doctorImage: {
    width: 100,
    height: 100,
    borderRadius: 50,
    marginBottom: 10,
  },
  doctorName: {
    fontSize: 22,
    fontWeight: 'bold',
    marginBottom: 5,
  },
  doctorSpecialty: {
    fontSize: 16,
    color: '#666',
    marginBottom: 10,
  },
  overallRatingContainer: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  starContainer: {
    flexDirection: 'row',
  },
  star: {
    marginHorizontal: 2,
  },
  overallRatingText: {
    marginLeft: 10,
    fontSize: 16,
    color: '#666',
  },
  commentSection: {
    backgroundColor: '#fff',
    marginHorizontal: 15,
    borderRadius: 10,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  commentLabel: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 10,
  },
  commentText: {
    fontSize: 16,
    marginBottom: 5,
  },
  ratingSection: {
    backgroundColor: '#fff',
    marginHorizontal: 15,
    borderRadius: 10,
    padding: 20,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  ratingSectionTitle: {
    fontSize: 18,
    fontWeight: 'bold',
    marginBottom: 15,
  },
  ratingOptionsContainer: {
    // flexDirection: 'column',
  },
  ratingOption: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 10,
  },
  ratingOptionText: {
    fontSize: 16,
    marginLeft: 5,
    marginRight: 10,
  },
  commentInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#fff',
    borderRadius: 25,
    marginHorizontal: 15,
    paddingHorizontal: 15,
    marginBottom: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 3,
  },
  cameraIcon: {
    marginRight: 10,
  },
  commentInput: {
    flex: 1,
    minHeight: 40,
    maxHeight: 100,
    color: '#000',
    paddingVertical: 10,
  },
  attachmentIcon: {
    marginLeft: 10,
  },
}); 